stages:
  - install
  - build

variables:
  SSH_PRIVATE_KEY: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBeU1qNGc4THpHOGhjT3diTTREZEZ4b1h6bC9Gam9XSFdNUkNKbHhNZElPYWI3L2xJCnFxSFowZXdaRUJFdFQzSG92aS8rNlVkeXByYnl5YzdkQTA1b2JTelhLUWVkb0t0ZUdudVFJRjRaS1lTTkdUVzEKekRDdHYzMzVBdnhJUWkweG5TaVpwUXJ2MmZOVkRybFpsUm13ZmJrTXE2YXF1OWNPSWdVcnRXK3RBclltbWRlYwptYWJHQjVMa1drb2hRckROdkhqTkdGK2pMa05VYTJqMFJkTmNKVUZqbGh0U3hUcmxTaG9jd3FScnVPOTcyc05NCkVVdGVQUUNIZXNEdkRUYWtLZXd3S1VrU0c1Y1dHZTB0Wk5TbTZKSVJreGEvU3lkN2Fua1ZsTjNDamlWRVJpTDAKQy90K3dPNW1jQzZzcklzWGk5YnRYTWJtaHBnUXJ2WHlDcEduNlFJREFRQUJBb0lCQVFDZGtscTF6UUROQk9pYwp5akZ1cFBIMVlwcFEyL2U4WnZPWmZjajg3dHNsUHRXUjlxaTRnRnhaQ2xpQTYzb0xwdkZva0hJVTBTV0JBSUo1CkxnYjAyVXZLb2k0WTNRa3ZWazE3cXd6bzJmQVZUUmtPZDhBOGh0ZFVPS0I3WDFHMTNaSGFMRXFuNDNWb0xqYksKWDF1V1Q1cmFqNmNKN3JwK3Y3OHZvNjh4ckhxeWJLd2NtaGowc1dRUVBOVXNkTUNQemhwMnlyZ2wremp5a2ZWVgp2U0NlbExCVzB5L2NuQkswcDJkd1B0elNKVm5OcFZ5TnY4RVpVVFUyMmU1TFFXeUtkR3E1MFF4aVFrK25YSkZnCkdwejF5aEo1TkpFa2tnUFlHQjY5L2g3OGoyQlA1SHZFWDB1cUxDbU5tN3RwbFlNcHd0MzFpQVRFQ01DV2x4QzQKcVY1cVZvaUJBb0dCQVBMZS9XQkZoZHRKTzg3SGJpNVNqdjFucitSbmQxc3FTN0tVQkNPL3YxZ2xSbVVDcE1mTQpGYkF6b1BvOXhZeFg1Ym1sbUNJUnVyWkdqTjNxcHJGUHRHdXZ5cUlyVTFNbmloQ2cwLzJId1FhQmtwTDc5WEJTCmI4ZDNhME5PUWJFTEJySEJRVWdyUDJaSDlXQkoxdHlmRHZlMm1jcVVvOGczT3RQMWtYaHAzTDdsQW9HQkFOT2oKa1NPYlVIVXdJOWx3a0tBTkFnYkhyYU5JTkhZak5oSGE5eDZyelB1ZXpadE9qajBwZy85VlJ1L2REMlNadEowSwpZWVlFRjgrZmFSV2xyNlVzRlRWcmRXeHlqdUhvRlgvUXVLM1BsU2lIZEt2Nm41MDAzWDliYjhybFZxMndLOXFXCmxnT1gwM045dzcySVFUWWRKTTBxWWhPMXRvd1lpTTJoQXpOVDZQQzFBb0dCQUprc3BCYTBva0IwQnFGYVRCWXgKQVhlMmprdDZLZCs0WkRlRGZMempNUld4cEowT05zaS80U25ZMWYwZE9sdFNFRk91cWExTEN6dnNjT21CRlpLYwpsMGlYZlRBY0xSZ3p4ckxJREF0Sk5DY2JUMHNlVjJSNHlZQyt3MHFXcjMydVc1RitOZU1EUzZBQllETlRQb3kwClVHZFFwZHdMTk9TUVdLelhvdUNUdTZJMUFvR0JBTG9MSUl4bmZQdjNYSnhKcXFrM3BoOWxxc3ROcnVobkhhSG0KbGJQOW5JMVkxUytBaCtOV09uWGJkaWRuY1oraXlyWCtLU3JSTUVsUXZlVE1xTElQSlhtM1JCc1lQV2h6UjJyNwpoVTB0bk5acTlQSTF0OWhQWDZNVU14cnVMaHN6TWVuTzFJTEdGWmlCNXU4Vzl4UmwzRE1LM2Zxcms1Um1BT1NhCmRTREswNHU5QW9HQkFKMUFHbWZTbERvN2J6Z2IvK0ZxZS8yZVJuVHcvL29COVFCK3NTbkNzNkw2Z0xxK0hQTHIKR2ZYNW81OTNCaVBTdHFsZW85VUZTUzEvRTVUUER2cEZ1REJFbmZPNThGSHFkd3dwNUkwKy9RQnJHeVFtSFV5aQplMjM3SmpYWUdMOVNxcDVocnNzSXcvR0J1TVR1MFE1T3MzL0NQVkY2a3JXQThMUXJGQUlEazJrUQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
  PROJECT_PATH: "$CI_PROJECT_DIR"
  APP_OUTPUT_PATH: "$CI_PROJECT_DIR/dist/scrivania"
  ENVIRONMENT: "stage"
  APP_PATH: "scrivania"

# Configuration shared for all jobs
default:
  # It saves ~10 sec to pull image from project container registry
  # instead of the default docker.io registry
  image: node:20.14
  tags:
    - babel

# Define an hidden job to be used with extends
# Better than default to avoid activating cache for all jobs
.dependencies_cache:
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
 
install_dependencies:
  stage: install
  script:
    - npm config set registry http://gdml.internal.ausl.bologna.it:4873/ -g
    - npm config set fetch-retry-mintimeout 5 -g
    - npm config set fetch-retry-maxtimeout 5 -g
    - yarn install
    # Redefine cache to have default pull-push policy
  extends: .dependencies_cache
  cache:
    policy: pull-push
  only:
    changes:
      - yarn.lock

build_app:
  stage: build
  script:
    - echo "$SSH_PRIVATE_KEY"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - yarn build --configuration=$ENVIRONMENT --base-href /$APP_PATH/
  after_script:
    - scp -r $APP_OUTPUT_PATH/* nodejs@gdml.internal.ausl.bologna.it:/opt/uis/scrivania-ui/dist/
  artifacts:
    name: "angular-app-pipeline"
    paths:
      - $APP_OUTPUT_PATH
  extends: .dependencies_cache
