stages:
  - install
 
install_dependencies:
  stage: install
  image: node:20.14
  tags:
    - babel
  script:
    - yarn install
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  only:
    refs:
      - merge_requests
      - gdm