stages:
  - install
  - build

variables:
  PROJECT_PATH: "$CI_PROJECT_DIR"
  APP_OUTPUT_PATH: "$CI_PROJECT_DIR/artifacts/app"
  ENVIRONMENT: "stage"
  APP_PATH: "scrivania"

# Configuration shared for all jobs
default:
  # It saves ~10 sec to pull image from project container registry
  # instead of the default docker.io registry
  image: node:20.14
  tags:
    - babel

# Define an hidden job to be used with extends
# Better than default to avoid activating cache for all jobs
.dependencies_cache:
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
 
install_dependencies:
  stage: install
  script:
    - npm config set registry http://gdml.internal.ausl.bologna.it:4873/ -g
    - npm config set fetch-retry-mintimeout 5 -g
    - npm config set fetch-retry-maxtimeout 5 -g
    - yarn install
    # Redefine cache to have default pull-push policy
  extends: .dependencies_cache
  cache:
    policy: pull-push
  only:
    changes:
      - yarn.lock

build_app:
  stage: build
  script:
    - yarn install
    - yarn build --configuration=stage --base-href /scrivania/ --output-path dist
  after_script:
    - cp $PROJECT_PATH/Dockerfile $APP_OUTPUT_PATH
  artifacts:
    name: "angular-app-pipeline"
    paths:
      - $APP_OUTPUT_PATH
  extends: .dependencies_cache
