import { ColonnaBds } from "@bds/common-tools";
import { FILTER_TYPES } from "@bds/next-sdr";

export const cols: ColonnaBds[] = [
  {
    field: "id",
    header: "Id",
    filterField: "id",
    // sortField: "idAzienda.nome",
    style: {},
    headerClass: ["header-column", "id-column"],
    filterClass: ["filter-column", "id-column"],
    bodyClass: ["id-column"],
    fieldType: "number",
    filterMatchMode: FILTER_TYPES.not_string.equals,
    useFilterMatchMode: true,
    default: true,
  },
  {
    field: "name",
    header: "Name",
    filterField: "idAzienda.id",
    // sortField: "idAzienda.nome",
    style: {},
    headerClass: ["header-column", "name-column"],
    filterClass: ["filter-column", "name-column"],
    bodyClass: ["name-column"],
    fieldType: "string",
    filterMatchMode: FILTER_TYPES.string.containsIgnoreCase,
    useFilterMatchMode: true,
    default: true,
  },
  {
    field: "state",
    header: "State",
    filterField: "idAzienda.id",
    // sortField: "idAzienda.nome",
    style: {},
    headerClass: ["header-column", "state-column"],
    filterClass: ["filter-column", "v-column"],
    bodyClass: ["ente-column"],
    fieldType: "object",
    filterMatchMode: FILTER_TYPES.not_string.equals,
    useFilterMatchMode: true,
    default: true,
  },
  {
    field: "error",
    header: "Error",
    filterField: "idAzienda.id",
    // sortField: "idAzienda.nome",
    style: {},
    headerClass: ["header-column", "error-column"],
    filterClass: ["filter-column", "error-column"],
    bodyClass: ["error-column"],
    fieldType: "string",
    filterMatchMode: FILTER_TYPES.string.containsIgnoreCase,
    useFilterMatchMode: true,
    default: true,
  },
  {
    field: "data",
    header: "Data",
    filterField: "idAzienda.id",
    // sortField: "idAzienda.nome",
    style: {},
    headerClass: ["header-column", "data-column"],
    filterClass: ["filter-column", "data-column"],
    bodyClass: ["data-column"],
    fieldType: "string",
    filterMatchMode: FILTER_TYPES.string.containsIgnoreCase,
    useFilterMatchMode: true,
    default: true,
  },
  {
    field: "set",
    header: "Set",
    filterField: "set",
    // sortField: "idAzienda.nome",
    style: {},
    headerClass: ["header-column", "set-column"],
    filterClass: ["filter-column", "set-column"],
    bodyClass: ["set-column"],
    fieldType: "number",
    filterMatchMode: FILTER_TYPES.not_string.equals,
    useFilterMatchMode: true,
    default: true,
  },
];
